import {Toaster} from "sonner";
import type { Metadata } from "next";
import localFont from "next/font/local";
import {Poppins} from "next/font/google";
import "./globals.css";
import { Provider } from "./provider";

const poppins=Poppins({
  subsets:["latin"],
  weight:["300","400","500","600","700"]
})
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Provider>
          {children}
          <Toaster richColors position="top-center"/>
        </Provider>
        
      </body>
    </html>
  );
}
